### PR TITLE
Added x-code for syntax highlighting of code snippets

### PR DESCRIPTION
**Pull request by twobit**
Usage:

``` html
<x-code>function() {
    console.log('hi');
}</x-code>
```

Supports an optional `data-lang` attribute to specify language.

Uses highlight.js (http://softwaremaniacs.org/soft/highlight/en/)

### CODE REVIEW

**Comment by csuwildcat** [comment]
I reviewed your module and saw that the content is only evaluated onInsert. We are aiming to have supported tags be as responsive and native feeling as possible. I'd like it if you retooled it so that when new content was added to the tag via innerHTML or text, that it re-highlight. For an example of this in tags today: select elements show their option children immediately, and can have options dynamically added to them - this current x-code tag implementation would be like a select element that, once appended to the DOM, could never have new options added to and, essentially non-declaritive and frozen. Does that make sense?

**Comment by twobit** [comment]
Added text getter/setter to improve usability of x-code. Let me know if there's any other concerns.

**Comment by twobit** [comment]
Great suggestion, updated!

**Comment by csuwildcat** [comment]
The tag registry launches this week, I'll post further details here when it goes live. Adding your custom tag is simple, you'll just add our web hook to your repo, and an xtag.json file to tell us a bit about your tag - we do the rest!

**Comment by pennyfx** [comment]
The registry is live.  Please checkout http://registry.x-tags.org and click on "Contribute Tags" to see how to add your tag.

**Comment by twobit** [comment]
I followed the instructions on the x-tag registry page but I'm not seeing the tag included in the registry.

I see entries in the logs:
http://registry.x-tags.org/logs/twobit

The repo was tagged as well. Any ideas?

https://github.com/twobit/x-tag-contrib

**Comment by pennyfx** [comment]
Can you try again?  I made a few changes to the registry yesterday.

**Comment by twobit** [comment]
Just pushed and saw this in the logs:

```
2012-7-31 11:50:57 :: Webhook isn't for x-tag registry, ignoring... [refs/heads/master]
```

My repo is tagged as mentioned in the docs:

```
# create a tag 
git tag xtag-v0.0.1 
# push it
git push --tags
```

**Comment by pennyfx** [comment]
The [refs/heads/master] tells me that it wasn't a new tag.  Can you try
bumping the version and creating another tag?

**Comment by twobit** [comment]
Created a new tag and bumped version, no dice:

```
git tag xcode-v0.0.3
git push --tags
```

```
2012-7-31 22:16:33 :: Webhook isn't for x-tag registry, ignoring... [refs/tags/xcode-v0.0.3]
```

**Comment by csuwildcat** [comment]
I believe that is the wrong tag token, your repo tag must begin with the
string "xtag". The docs are terrible in this regard and should be changed
to clarify that this is required. (can you confirm this requirement arron?)

**Comment by twobit** [comment]
Thanks! I see the tag in the registry now

**Pull request closed without merging**
