### PR TITLE
Improve styling and markup for index and demo pages.

### PR DESCRIPTION
**Pull request by karthikv**
The home and demo pages could have clearer typography, a more intuitive navigation, more whitespace in the main content area for readability, and, in the case of the demo page, more styling for some of the elements. This pull request addresses these concerns. I've included two screenshots of my changes—one for the home page and one for the demo page—below:
## Home Page

Index page
## Demo Page

Index page

### CODE REVIEW

**Comment by csuwildcat** [comment]
Our focus at this time is not on the style of the pages, but on making the actual X-Tag web components polyfill/lib as streamlined and solid as possible. We may assess styles at a later time, but after releasing a style just a couple weeks ago, I am not inclined to take in style modifications unless there is some actual out cry or the current styles can be show to somehow affect usability (your comment about navigation is probably worth inclusion, a textual menu up top might be a good change).

**Comment by karthikv** [comment]
Although I understand you are not focused on the design of the demo pages, this doesn't mean that it can't be improved. At the point where integrating these style changes only constitutes merging the commit that I have made in this pull request—which I doubt should take more than 30 minutes, at max—you do not necessarily need to be focused on style changes to include them.

Regarding your point about not being inclined to merge the changes unless there is an outcry, I urge you to reconsider. There does not need to be an outcry to validate changing styles; quite the contrary, designs always go through iteration. I suggest assessing the more logical question of whether or not the proposed design change will make the site more appealing to users. After all, this is the ultimate goal of any design.

And, indeed, there are problems with the current styling. I do not intend to discredit the original designer of the site; quite the contrary, I only want to help improve it, as evidenced by this pull request. Since form follows design, it is of importance that the following issues, among others, are addressed:
- The "Custom HTML Elements..." is very gray and, for me, quite difficult to read. I would think an elderly man/woman visiting the site would have even further trouble with this same text.
- Line height could be increased in the main text area to allow for further readability. Research dictates that people generally prefer around a 1.5 line spacing on the web.
- The header bar does not need to span the whole browser window; not only is it given too much focus, but the X-Tag logo and navigation are far too disjointed from the content area. I didn't even realize the navigation was in the top right until digging down into the code behind the site.
- On the examples page, the buttons could use padding to clarify their text and function.
- Some example elements, such as the pagination towards the bottom, lack styles all together. To both show off X-Tag elements and help gain user adoption, it would be beneficial to make the demo pages look appealing.

Indeed, even though some of the changes that I've proposed may not necessarily seem to improve usability directly, it's important to consider aesthetic appeal. I believe the changes I've made enhance the aesthetics of the site, ultimately resulting in a more pleasurable experience for the user. This too should be a priority in determining whether to integrate these changes.

Ultimately, my point is that integrating these style changes does not come down to whether you are focused on this topic or whether there is an outcry for alterations. What matters is simply what users think. I suggest polling people on which design they prefer and assessing the results. If they prefer the design I have created, merging it in won't take long at all. If they prefer the current design, leave the site as is; in other words, evaluate this design on what matters: whether this will make the site more appealing to users.

**Comment by csuwildcat** [comment]
I'll briefly address your comments:
- "The Custom HTML Elements... is very gray and, for me, quite difficult to read" - It is a _watermark_, it's intended to be subtle
- "Line height could be increased in the main text area to allow for further readability. Research dictates that people generally prefer around a 1.5 line spacing on the web." --> this is a preference, this very website, github.com, uses the default line spacing, as do most sites on the web.
- "The header bar does not need to span the whole browser window; not only is it given too much focus, but the X-Tag logo and navigation are far too disjointed from the content area." - a valid points here, the logo should link back to the main gh-pages index
- "Some example elements, such as the pagination towards the bottom, lack styles all together. To both show off X-Tag elements and help gain user adoption, it would be beneficial to make the demo pages look appealing." - the demos and the default state of all custom tags we are generating are intended to have as close to zero style applied to them as possible. These are building blocks, not pretty twitter bootstrap widgets. You should think of these elements as near-native lacking any and all presentational styling when possible - for example, you would not expect a UL to come with extravagant bullet icon images, or borders and margins for its LIs.

I honestly don't have time to run a poll on this right now, please focus on the actual X-Tag library code and creating custom tags, these are far more important items for the project.

**Comment by cvan** [comment]
would it hurt things if this was pulled in? it looks nice.

**Comment by michaelkrog** [comment]
It hurts the focus on the project.

**Comment by csuwildcat** [comment]
Below is a critique of the visual changes proposed, consider the following:

index page design critique

What I can agree on:
- Fixed positioning of header can probably go
- Logo should have X-Tag in text next to it

**Pull request merged**
