### PR TITLE
Code cleanups, replacing of tabs and documentation

### PR DESCRIPTION
**Pull request by yorickpeterse**
This pull request is currently still a work in progress but is meant to address
the following:
- spaces should be used for indentation, see #28
- inconsistent use of whitespace, statements (`if`, `for`, etc)
- various jslint errors (those that made sense to me)
- documentation

In the current set of commits I've addressed the first 3 items as much as I
could. However, I can imagine that my coding style may differ from the one used
at Mozilla or for this specific project. If this is the case and it has to be
changed I'll be happy to do so.

The last item, documentation, will be addressed in coming commits which I'll
probably push somewhere this evening (GMT+2), otherwise they'll be pushed
tomorrow.

While cleaning up the code I might have broken something so it's wise to verify
the code in different browsers before accepting (or denying) it. I've tested it
in Chromium 19 and it works fine. However, both my local copy as well as the
online version on Github don't seem to work in Firefox 13.

Last but not least: feedback welcome :)

### CODE REVIEW

**Comment by seanmonstar** [comment]
See https://github.com/mozilla/webdev-bootcamp/blob/master/js-style.rst#conditionals-and-loops for javascript style guide. Specially, a space after the parens in `function() {` and spaces after keywords like if, for, while, switch: `if (x) {`.

**Comment by yorickpeterse** [comment]
@seanmonstar Good call, I already figured the styling of the statements was a bit weird but this was what I saw in the existing code base. I'll take a look at the style guide and fix the code accordingly.

**Comment by fwenzel** [comment]
@csuwldcat will it be fine if I merge this? I really do think we should apply Mozilla coding guidelines to this project. Just set your editor to soft tabs and you won't even notice the difference, I promise :)

FWIW, this pull request has some nice smaller cleanups and docstrings too.

**Comment by csuwildcat** [comment]
We cannot use ES5 strict mode for this library as it would significantly reduce compatibility on Safari, Opera (desktop & mobile), Android, and iOS.

**Comment by yorickpeterse** [comment]
What parts actually wouldn't work when enabling strict mode?

**Comment by yorickpeterse** [comment]
Just a small heads up, I'm currently quite busy so I probably won't have time to finish this pull request until this weekend.

**Comment by jlongster** [comment]
This looks like a good PR, and I'd hate to let it bitrot. Can an owner please merge this in?

**Comment by pennyfx** [comment]
I took most of what I could and merged it manually.  I'm closing this pull.

**Pull request closed without merging**
