### PR TITLE
strip all trailing whitespace!

### PR DESCRIPTION
**Pull request by cvan**
There's a whole lotta trailing whitespace. It'd be nice to not have all of it. This patch attempts changes that.

I handle it in my text editor, but I've known people to add these links to `~/.gitconfig`:

```
[core]
    whitespace = trailing-space,space-before-tab
[apply]
    whitespace = fix
```

### CODE REVIEW

**Comment by fwenzel** [comment]
Needless to say this can't be merged anymore ;) Can you patch it up? I can land it as soon as you do.

**Comment by cvan** [comment]
Why can't this be merged anymore? In the original there may or may not have been a bad merge conflict. But I rebased and pushed a fix. Is there something else?

**Comment by fwenzel** [comment]
Uh, lemme rephrase: I can't press the convenient green "merge" button any longer. I gave you push rights. Just rebase and push. Thanks!

**Comment by pennyfx** [comment]
I'm taking care of this.

**Comment by fwenzel** [comment]
Thanks arron!

**Pull request closed without merging**
