### PR TITLE
Don't use document, use doc

### PR DESCRIPTION
**Pull request by darkwing**
Already aliasing doc, don't need to use document ever.

### CODE REVIEW

**Comment by tofumatt** [comment]
Is typing the extra five characters that much of a pain? Given that it's more or less a constant global variable and developers already know what you mean by `document`, this seems like overkill in the name of a few bytes that are pre-uglify.

**Comment by darkwing** [comment]
"doc" is already defined in x-tag, so it should either be used or not used;  not both

**Comment by tofumatt** [comment]
Yeah, I'm just arguing for the latter.

**Comment by darkwing** [comment]
I originally moved toward `doc` because:
1.  It's a known alias within most JS libs
2.  It's a boost for minification

Feel free to remove as seen fit.

**Pull request merged**
